### ISSUE TITLE
Game won't take any guesses

### ISSUE THREAD

**Issue by mhoney** [milesdyck/logos64#1]
I've downloaded v2.03 and am running it in WinVICE 3.1, but after I choose a game, either random or by date, the game won't accept any letters I use.  After I fill in a row of letters and press return, it just blanks out the letters and puts the cursor back at the beginning of row 1.

**Comment by milesdyck** [comment]
Sorry to hear of your problems.

I downloaded the disk image from the repository (
https://github.com/milesdyck/logos64/blob/main/logos2024v203.d64) and
tested it and it worked on my computer running VICE 3.6.1.

When you attach the disk image in VICE, make sure you select device 8.

Make sure you are only using ",8" when you load it: LOAD"LOGOSBIN.VEX",8

If it still doesn't work, you may need to download and install VICE 3.6.1
or higher - https://vice-emu.sourceforge.io/index.html#download

Let me know if you continue to have issues.

Miles
